dashboard/urls.py
from django.contrib import admin
from django.urls import path
from companies import views

urlpatterns = [
    path('', views.home, name='home'),
    
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.signout, name='logout'),
    
    # Companies URLs
    path('companies/data', views.home_data_json, name='companies_data'),
    path('company/<int:company_id>/detail', views.company_data_json, name='company_detail'),
    path('companies/', views.companies, name='companies'),
    path('company_create/', views.company_create, name='company_create'),
    path('company/<int:company_id>', views.company_detail, name='company_detail'),
    path('company/<int:company_id>/delete', views.company_delete, name='company_delete')
]

companies/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
risk_qualifier = (
        ('0','?'),
        ('1','Aaa'),
        ('2','Aa1'),
        ('3','Aa2'),
        ('4','Aa3'),
        ('5','Baa1'),
        ('6','Baa2'),
        ('7','Baa3'),
    )

risk_type = (
        ('0', 'Pendiente'),
        ('1', 'Riesgo de crédito'),
        ('2', 'Riesgo de mercado'),
        ('3', 'Riesgo de liquidez'),
        ('4', 'Riesgo operativo'),
        ('5', 'Riesgo regulatorio'),
        ('6', 'Riesgo de reputación'),
    )

class Company(models.Model):
    name = models.CharField(blank=False,max_length=60,null=False)
    sector = models.CharField(blank=False,max_length=60,null=False)
    risk_qualifier = models.CharField(default='?',choices=risk_qualifier,null=False,max_length=1)
    risk_type = models.CharField(default=0,choices=risk_type,null=False,max_length=2)
    risk_rating = models.DecimalField(blank=False,null=False,decimal_places=2,max_digits=3)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Empresa"
        verbose_name_plural = "Empresas"

    def __str__(self):
        return self.name+ ' - ' + self.sector
    
    def risk_rating_percentage(self):
        return int(self.risk_rating * 100)

companies/forms.py
from django.forms import ModelForm
from .models import Company

class CompanyForm(ModelForm):
    class Meta:
        model = Company
        fields = [
            'name',
            'sector',
            'risk_qualifier',
            'risk_type',
            'risk_rating'
        ]

companies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Company
from .forms import CompanyForm

from django.core.serializers import serialize
from django.http import HttpResponse

# Create your views here.
# Main public view
def home(request):
    return render(request, 'home.html')

def home_data_json(request):
    if request.method == 'GET':
        data = Company.objects.all()
        data = serialize("json", data, fields=('name', 'sector', 'risk_rating'))
        return HttpResponse(data, content_type="application/json")
    
def company_data_json(request, company_id):
    if request.method == 'GET':
        data = Company.objects.filter(pk=company_id)
        if len(data) == 1:
            data = serialize("json", data, fields=('name','sector','risk_rating'))
        else:
            data = [{"code":"500", "message": "No hemos encontrado la información de la empresa"}]

    return HttpResponse(data, content_type="application/json")

# REGISTER (create a new user account)
def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {"form": UserCreationForm})
    else:

        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    request.POST["username"], password=request.POST["password1"])
                user.save()
                login(request, user)
                return redirect('companies')
            except IntegrityError:
                return render(request, 'signup.html', {"form": UserCreationForm, "error": "El nombre de usuario ya existe."})

        return render(request, 'signup.html', {"form": UserCreationForm, "error": "Las contraseñas no coinciden."})

# LOGIN
def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {"form": AuthenticationForm})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'signin.html', {"form": AuthenticationForm, "error": "Usuario o contraseña incorrectos."})

        login(request, user)
        return redirect('companies')
    
# LOGOUT (close session)
@login_required
def signout(request):
    logout(request)
    return redirect('home')

# GET ALL COMPANIES
@login_required
def companies(request):
    companies = Company.objects.filter(user=request.user)
    return render(request, 'companies.html', {"data": companies})

# CREATE COMPANIES
@login_required
def company_create(request):
    if request.method == "GET":
        return render(request, 'company_create.html', {"form": CompanyForm})
    else:
        try:
            form = CompanyForm(request.POST)
            new_company = form.save(commit=False)
            new_company.user = request.user
            new_company.save()
            return redirect('companies')
        except ValueError:
            return render(request, 'company_create.html', {
                "form": CompanyForm, 
                "error": "Ocurrio un error al crear la empresa."
            })
 
# GET A COMPANY BY ID
@login_required
def company_detail(request, company_id):
    if request.method == 'GET':
        company = get_object_or_404(Company, pk=company_id, user=request.user)
        form = CompanyForm(instance=company)
        return render(request, 'company_detail.html', {
            'data': company, 'form': form
        })
    else:
        try:
            company = get_object_or_404(Company, pk=company_id, user=request.user)
            form = CompanyForm(request.POST, instance=company)
            form.save()
            return redirect('companies')
        except ValueError:
            return render(request, 'company_detail.html', {
                'company': company, 'form': form, 'error': 'Ocurrio un error al actualizar la empresa.'
            })

# DELETE A COMPANY
@login_required
def company_delete(request, company_id):
    company = get_object_or_404(Company, pk=company_id, user=request.user)
    if request.method == 'POST':
        company.delete()
        return redirect('companies')

companies/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="/companies" class="nav-link">Empresas</a>
                </li>
                <li class="nav-item">
                    <a href="/logout" class="nav-link">Salir</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="/signin" class="nav-link">Ingreso</a>
                </li>
                <li class="nav-item">
                    <a href="/signup" class="nav-link">Registo</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

companies/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.7.0.slim.min.js" integrity="sha256-tG5mcZUtJsZvyKAxYLVXrmjKBVLd6VpVccqz/r4ypFE=" crossorigin="anonymous"></script>
</head>

<body>
    {% include '_navbar.html' %}

    {% block content %}
    {% endblock %}
</body>

</html>

companies/templates/companies.html
{% extends 'base.html' %} {% block content %}

<style>
    .btn-flotante {
        font-size: 16px;
        /* Cambiar el tamaño de la tipografia */
        text-transform: uppercase;
        /* Texto en mayusculas */
        font-weight: bold;
        /* Fuente en negrita o bold */
        color: #ffffff;
        /* Color del texto */
        border-radius: 5px;
        /* Borde del boton */
        letter-spacing: 2px;
        /* Espacio entre letras */
        background-color: #198754;
        /* Color de fondo */
        padding: 18px 30px;
        /* Relleno del boton */
        position: fixed;
        bottom: 40px;
        right: 40px;
        transition: all 300ms ease 0ms;
        box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
        z-index: 99;
    }

    .btn-flotante:hover {
        color: #ffffff;
        opacity: .95;
        /* Color de fondo al pasar el cursor */
        box-shadow: 0px 15px 20px rgba(0, 0, 0, 0.3);
        transform: translateY(-7px);
    }

    @media only screen and (max-width: 600px) {
        .btn-flotante {
            font-size: 14px;
            padding: 12px 20px;
            bottom: 20px;
            right: 20px;
        }
    }
</style>

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.dataTables.min.css">
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"
    integrity="sha512-qZvrmS2ekKPF2mSznTQsxqPgnpkI4DNTlrdUmTzrDgektczlKNRRhy5X5AAOnx5S09ydFYWWNSfcEqDTTHgtNA=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<div class="container">

    <div class="card mt-4">
        <div class="card-body">
            <h1>Empresas</h1>

            <table class="table table-bordered mt-4" id="table_companies">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Sector</th>
                        <th scope="col">Calificador de riesgo</th>
                        <th scope="col">Tipo de Riesgo</th>
                        <th scope="col">Ponderación</th>
                        <th scope="col">*</th>
                    </tr>
                </thead>
                <tbody>
                    {% for company in data %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{company.name}}</td>
                        <td>{{company.sector}}</td>
                        <td>{{company.get_risk_qualifier_display}}</td>
                        <td>{{company.get_risk_type_display}}</td>
                        <td>{{company.risk_rating_percentage}}%</td>
                        <td>
                            <span class="d-flex gap-2">
                                <form action="{% url 'company_delete' company.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm btn-danger" title="Eliminar">
                                        <i class="fa-solid fa-trash"></i>
                                    </button>
                                </form>

                                <a href="{% url 'company_detail' company.id %}" class="btn btn-sm btn-primary"
                                    title="Editar">
                                    <i class="fa-solid fa-pen"></i>
                                </a>

                                <button type="button" class="btn btn-sm btn-success btn_risk_company"
                                    data-bs-toggle="modal" data-bs-target="#modalCompanyRisk"
                                    title="Calificador de riesgo" company="{{company.id}}">
                                    <i class="fa-solid fa-bolt"></i>
                                </button>
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="/company_create/" class="btn-flotante">Nueva empresa</a>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="confirm" tabindex="-1" aria-labelledby="confirmLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="confirmLabel">¿Estas seguro?</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Si pulsas en <b>Eliminar</b>, se borrará por completo la información de la empresa.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-danger">Eliminar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modalCompanyRisk" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="modalCompanyRiskLabel" aria-hidden="true">
        <div class="modal-dialog modal-fullscreen">
            <div class="modal-content">
                <div class="modal-body">

                    <div class="card" id="card_company_info">
                        <div class="card-header" id="company_name">
                            Empresa
                        </div>
                        <div class="card-body d-flex justify-content-center">
                            <div class="w-75">
                                <canvas id="chart_risk_company"></canvas>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success btn_export">Exportar</button>
                    <button type="button" class="btn btn-primary">Simular Probabilidades</button>
                    <button type="button" class="btn btn-secondary btn_close_risk_company"
                        data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        const RISK_QUALIFIER = ['Aaa', 'Aa1', 'Aa2', 'Aa3', 'Baa1', 'Baa2', 'Baa3'];
        const RISK_TYPES = [
            'Pendiente',
            'Riesgo de crédito',
            'Riesgo de mercado',
            'Riesgo de liquidez',
            'Riesgo operativo',
            'Riesgo regulatorio',
            'Riesgo de reputación'
        ];

        const table = $('#table_companies').DataTable({
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.13.6/i18n/es-ES.json',
            },
            dom: 'Bfrtip',
            buttons: [
                'excel', 'pdf'
            ]
        });

        let myChart;
        $(".btn_risk_company").click(async function () {
            openFullscreen()

            const id = $(this).attr("company");
            const result = await fetch("https://django-app-o63u.onrender.com/company/" + id + "/detail", {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                }
            });
            let detail = await result.json();
            $("#company_name").html(
                `<b>Nombre:</b> ${detail[0].fields.name}&nbsp;   <b>Sector:</b> ${detail[0].fields.sector}`
            )


            const ctx = document.getElementById('chart_risk_company');

            const data = {
                labels: RISK_QUALIFIER,
                datasets: [{
                    label: 'Calificadores de riesgo',
                    data: [100, 85, 70, 65, 50, 45, 30],
                    backgroundColor: [
                        'rgba(255, 26, 104, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(0, 0, 0, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 26, 104, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(0, 0, 0, 1)'
                    ],
                    borderWidth: 1
                }, {
                    type: 'line',
                    label: detail[0].fields.name,
                    data: [parseFloat(detail[0].fields.risk_rating) * 100],
                    backgroundColor: ['rgb(0,0,0)'],
                    borderColor: ['rgba(0,0,0,0.2)']
                }
                ]
            };

            const config = {
                type: 'bar',
                data,
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            };

            myChart = new Chart(ctx,
                config
            );
        })

        $(".btn_close_risk_company").click(function () {
            if (myChart) {
                myChart.destroy();
            }
            closeFullscreen()
        })

        $(".btn_export").click(function () {
            window.print();
        })

        /* CREDIT TO https://www.w3schools.com/howto/howto_js_fullscreen.asp */

        const doc = document.documentElement;
        /* View in fullscreen */
        function openFullscreen() {
            if (doc.requestFullscreen) {
                doc.requestFullscreen();
            } else if (doc.webkitRequestFullscreen) { /* Safari */
                doc.webkitRequestFullscreen();
            } else if (doc.msRequestFullscreen) { /* IE11 */
                doc.msRequestFullscreen();
            }
        }
        /* Close fullscreen */
        function closeFullscreen() {
            if (document.exitFullscreen) {
                document.exitFullscreen();
            } else if (document.webkitExitFullscreen) { /* Safari */
                document.webkitExitFullscreen();
            } else if (document.msExitFullscreen) { /* IE11 */
                document.msExitFullscreen();
            }
        }

    });
</script>
{% endblock %}

companies/templates/company_create.html
{% extends 'base.html' %}

{% block content %}
<h1>Nueva Empresa</h1>

{{error}}
<form action="/company_create/" method="POST">
    {% csrf_token %}
    {{form}}

    <button class="btn btn-sm btn-success">Guardar</button>
</form>
{% endblock %}

companies/templates/company_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    {{data.title}}
    
    {{error}}
    
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        
        <button class="btn btn-sm btn-success">Actualizar</button>
        <a href="{% url 'companies' %}" class="btn btn-sm btn-danger">
            Cancelar
        </a>
    </form>
</div>
{% endblock %}

companies/templates/home.html
{% extends 'base.html' %} {% block content %}

<div class="container mt-3 d-flex justify-content-center">
  <div class="w-100">
    <canvas id="chart_companies"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

  <script>
    $(document).ready(async () => {
      const result = await fetch('https://django-app-o63u.onrender.com/companies/data', {
        headers: {
          'Content-Type': 'application/json',
        }
      });

      const companies = await result.json();

      let labelCompanies = [];
      let ratingCompanies = [];
      companies.forEach(element => {
        labelCompanies.push(element.fields.name)
        ratingCompanies.push(element.fields.risk_rating)
      });

      const ctx = document.getElementById('chart_companies');
      const data = {
        labels: labelCompanies,
        datasets: [{
          label: 'EMPRESAS (ponderación de riesgos en porcentaje)',
          data: ratingCompanies,
          backgroundColor: [
            'rgba(255, 99, 132, 0.2)',
            'rgba(255, 159, 64, 0.2)',
            'rgba(255, 205, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(54, 162, 235, 0.2)',
          ],
          borderColor: [
            'rgb(255, 99, 132)',
            'rgb(255, 159, 64)',
            'rgb(255, 205, 86)',
            'rgb(75, 192, 192)',
            'rgb(54, 162, 235)',
          ],
          borderWidth: 1,
          borderRadius: 5,
          borderSkipped: false,
        }]
      };
      new Chart(ctx, {
        type: 'bar',
        data: data,
        options: {
          scales: {
            y: {
              beginAtZero: true
            }
          }
        }
      });

    });
  </script>

</div>

{% endblock %}

companies/templates/signin.html
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" />
</head>

<body class="main-bg">
    <!-- Login Form -->
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="card shadow">
                    <div class="card-title text-center border-bottom">
                        <h2 class="p-3">Login</h2>
                    </div>
                    <div class="card-body">
                        <form action="/signin/" method="POST">
                            {% csrf_token %}
                            <div class="mb-4">
                                <label for="id_username" class="form-label">Usuario</label>
                                <input type="text" class="form-control" name="username" autofocus=""
                                    autocapitalize="none" autocomplete="username" maxlength="150" required=""
                                    id="id_username">
                            </div>
                            <div class="mb-4">
                                <label for="id_password" class="form-label">Contraseña</label>
                                <input type="password" class="form-control" name="password"
                                    autocomplete="current-password" required="" id="id_password">
                            </div>
                            <div class="d-grid">
                                <button type="submit" class="btn text-light main-bg">Ingresar</button>

                                <p class="d-flex justify-content-around mt-4">
                                    <a href="/signup" class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                                        Registrarme
                                    </a>
                                    
                                    <a href="/" class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                                        Home
                                    </a>
                                </p>
                            </div>
                        </form>

                        <p class="mt-3 text-danger fs-5 text-center">
                            {{error}}
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

<style>
    :root {
        --main-bg: #122330;
    }

    .main-bg {
        background: var(--main-bg) !important;
    }

    input:focus,
    button:focus {
        border: 1px solid var(--main-bg) !important;
        box-shadow: none !important;
    }

    .form-check-input:checked {
        background-color: var(--main-bg) !important;
        border-color: var(--main-bg) !important;
    }

    .card,
    .btn,
    input {
        border-radius: 0 !important;
    }
</style>

companies/templates/signup.html
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registro</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" />
</head>

<body class="main-bg">
    <!-- Login Form -->
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="card shadow">
                    <div class="card-title text-center border-bottom">
                        <h2 class="p-3">Registro</h2>
                    </div>
                    <div class="card-body">
                        <form action="/signup/" method="POST">
                            {% csrf_token %}
                            <div class="mb-4">
                                <label for="id_username" class="form-label">Usuario</label>
                                <input type="text" class="form-control" name="username" autofocus=""
                                    autocapitalize="none" autocomplete="username" maxlength="150" required=""
                                    id="id_username">
                            </div>
                            <div class="mb-4">
                                <label for="id_password" class="form-label">Contraseña</label>
                                <input class="form-control" type="password" name="password1" autocomplete="new-password"
                                    required="" id="id_password1">
                           </div>
                            <div class="mb-4">
                                <label for="id_password2" class="form-label">Confirmar Contraseña</label>
                                <input class="form-control" type="password" name="password2" autocomplete="new-password"
                                    required="" id="id_password2">
                           </div>
                            <div class="d-grid">
                                <button type="submit" class="btn text-light main-bg">Registrar</button>
                                
                                <p class="d-flex justify-content-around mt-4">
                                    <a href="/signin" class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                                        Login
                                    </a>
                                    
                                    <a href="/" class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                                        Home
                                    </a>
                                </p>

                            </div>
                        </form>

                        <p class="mt-3 text-danger fs-5 text-center">
                            {{error}}
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

<style>
    :root {
        --main-bg: #122330;
    }

    .main-bg {
        background: var(--main-bg) !important;
    }

    input:focus,
    button:focus {
        border: 1px solid var(--main-bg) !important;
        box-shadow: none !important;
    }

    .form-check-input:checked {
        background-color: var(--main-bg) !important;
        border-color: var(--main-bg) !important;
    }

    .card,
    .btn,
    input {
        border-radius: 0 !important;
    }
</style>